//
// Copyright (C) 2017 Tootbot Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

import UIKit

enum FontAwesome: String {
    case glass = "\u{f000}"
    case music = "\u{f001}"
    case search = "\u{f002}"
    case envelopeO = "\u{f003}"
    case heart = "\u{f004}"
    case star = "\u{f005}"
    case starO = "\u{f006}"
    case user = "\u{f007}"
    case film = "\u{f008}"
    case thLarge = "\u{f009}"
    case th = "\u{f00a}"
    case thList = "\u{f00b}"
    case check = "\u{f00c}"
    case times = "\u{f00d}"
    static var remove: FontAwesome { return .times }
    static var close: FontAwesome { return .times }
    case searchPlus = "\u{f00e}"
    case searchMinus = "\u{f010}"
    case powerOff = "\u{f011}"
    case signal = "\u{f012}"
    case cog = "\u{f013}"
    static var gear: FontAwesome { return .cog }
    case trashO = "\u{f014}"
    case home = "\u{f015}"
    case fileO = "\u{f016}"
    case clockO = "\u{f017}"
    case road = "\u{f018}"
    case download = "\u{f019}"
    case arrowCircleODown = "\u{f01a}"
    case arrowCircleOUp = "\u{f01b}"
    case inbox = "\u{f01c}"
    case playCircleO = "\u{f01d}"
    case `repeat` = "\u{f01e}"
    static var rotateRight: FontAwesome { return .repeat }
    case refresh = "\u{f021}"
    case listAlt = "\u{f022}"
    case lock = "\u{f023}"
    case flag = "\u{f024}"
    case headphones = "\u{f025}"
    case volumeOff = "\u{f026}"
    case volumeDown = "\u{f027}"
    case volumeUp = "\u{f028}"
    case qrcode = "\u{f029}"
    case barcode = "\u{f02a}"
    case tag = "\u{f02b}"
    case tags = "\u{f02c}"
    case book = "\u{f02d}"
    case bookmark = "\u{f02e}"
    case print = "\u{f02f}"
    case camera = "\u{f030}"
    case font = "\u{f031}"
    case bold = "\u{f032}"
    case italic = "\u{f033}"
    case textHeight = "\u{f034}"
    case textWidth = "\u{f035}"
    case alignLeft = "\u{f036}"
    case alignCenter = "\u{f037}"
    case alignRight = "\u{f038}"
    case alignJustify = "\u{f039}"
    case list = "\u{f03a}"
    case outdent = "\u{f03b}"
    static var dedent: FontAwesome { return .outdent }
    case indent = "\u{f03c}"
    case videoCamera = "\u{f03d}"
    case pictureO = "\u{f03e}"
    static var photo: FontAwesome { return .pictureO }
    static var image: FontAwesome { return .pictureO }
    case pencil = "\u{f040}"
    case mapMarker = "\u{f041}"
    case adjust = "\u{f042}"
    case tint = "\u{f043}"
    case pencilSquareO = "\u{f044}"
    static var edit: FontAwesome { return .pencilSquareO }
    case shareSquareO = "\u{f045}"
    case checkSquareO = "\u{f046}"
    case arrows = "\u{f047}"
    case stepBackward = "\u{f048}"
    case fastBackward = "\u{f049}"
    case backward = "\u{f04a}"
    case play = "\u{f04b}"
    case pause = "\u{f04c}"
    case stop = "\u{f04d}"
    case forward = "\u{f04e}"
    case fastForward = "\u{f050}"
    case stepForward = "\u{f051}"
    case eject = "\u{f052}"
    case chevronLeft = "\u{f053}"
    case chevronRight = "\u{f054}"
    case plusCircle = "\u{f055}"
    case minusCircle = "\u{f056}"
    case timesCircle = "\u{f057}"
    case checkCircle = "\u{f058}"
    case questionCircle = "\u{f059}"
    case infoCircle = "\u{f05a}"
    case crosshairs = "\u{f05b}"
    case timesCircleO = "\u{f05c}"
    case checkCircleO = "\u{f05d}"
    case ban = "\u{f05e}"
    case arrowLeft = "\u{f060}"
    case arrowRight = "\u{f061}"
    case arrowUp = "\u{f062}"
    case arrowDown = "\u{f063}"
    case share = "\u{f064}"
    static var mailForward: FontAwesome { return .share }
    case expand = "\u{f065}"
    case compress = "\u{f066}"
    case plus = "\u{f067}"
    case minus = "\u{f068}"
    case asterisk = "\u{f069}"
    case exclamationCircle = "\u{f06a}"
    case gift = "\u{f06b}"
    case leaf = "\u{f06c}"
    case fire = "\u{f06d}"
    case eye = "\u{f06e}"
    case eyeSlash = "\u{f070}"
    case exclamationTriangle = "\u{f071}"
    static var warning: FontAwesome { return .exclamationTriangle }
    case plane = "\u{f072}"
    case calendar = "\u{f073}"
    case random = "\u{f074}"
    case comment = "\u{f075}"
    case magnet = "\u{f076}"
    case chevronUp = "\u{f077}"
    case chevronDown = "\u{f078}"
    case retweet = "\u{f079}"
    case shoppingCart = "\u{f07a}"
    case folder = "\u{f07b}"
    case folderOpen = "\u{f07c}"
    case arrowsV = "\u{f07d}"
    case arrowsH = "\u{f07e}"
    case barChart = "\u{f080}"
    static var barChartO: FontAwesome { return .barChart }
    case twitterSquare = "\u{f081}"
    case facebookSquare = "\u{f082}"
    case cameraRetro = "\u{f083}"
    case key = "\u{f084}"
    case cogs = "\u{f085}"
    static var gears: FontAwesome { return .cogs }
    case comments = "\u{f086}"
    case thumbsOUp = "\u{f087}"
    case thumbsODown = "\u{f088}"
    case starHalf = "\u{f089}"
    case heartO = "\u{f08a}"
    case signOut = "\u{f08b}"
    case linkedinSquare = "\u{f08c}"
    case thumbTack = "\u{f08d}"
    case externalLink = "\u{f08e}"
    case signIn = "\u{f090}"
    case trophy = "\u{f091}"
    case githubSquare = "\u{f092}"
    case upload = "\u{f093}"
    case lemonO = "\u{f094}"
    case phone = "\u{f095}"
    case squareO = "\u{f096}"
    case bookmarkO = "\u{f097}"
    case phoneSquare = "\u{f098}"
    case twitter = "\u{f099}"
    case facebook = "\u{f09a}"
    static var facebookF: FontAwesome { return .facebook }
    case github = "\u{f09b}"
    case unlock = "\u{f09c}"
    case creditCard = "\u{f09d}"
    case rss = "\u{f09e}"
    static var feed: FontAwesome { return .rss }
    case hddO = "\u{f0a0}"
    case bullhorn = "\u{f0a1}"
    case bell = "\u{f0f3}"
    case certificate = "\u{f0a3}"
    case handORight = "\u{f0a4}"
    case handOLeft = "\u{f0a5}"
    case handOUp = "\u{f0a6}"
    case handODown = "\u{f0a7}"
    case arrowCircleLeft = "\u{f0a8}"
    case arrowCircleRight = "\u{f0a9}"
    case arrowCircleUp = "\u{f0aa}"
    case arrowCircleDown = "\u{f0ab}"
    case globe = "\u{f0ac}"
    case wrench = "\u{f0ad}"
    case tasks = "\u{f0ae}"
    case filter = "\u{f0b0}"
    case briefcase = "\u{f0b1}"
    case arrowsAlt = "\u{f0b2}"
    case users = "\u{f0c0}"
    static var group: FontAwesome { return .users }
    case link = "\u{f0c1}"
    static var chain: FontAwesome { return .link }
    case cloud = "\u{f0c2}"
    case flask = "\u{f0c3}"
    case scissors = "\u{f0c4}"
    static var cut: FontAwesome { return .scissors }
    case filesO = "\u{f0c5}"
    static var copy: FontAwesome { return .filesO }
    case paperclip = "\u{f0c6}"
    case floppyO = "\u{f0c7}"
    static var save: FontAwesome { return .floppyO }
    case square = "\u{f0c8}"
    case bars = "\u{f0c9}"
    static var navicon: FontAwesome { return .bars }
    static var reorder: FontAwesome { return .bars }
    case listUl = "\u{f0ca}"
    case listOl = "\u{f0cb}"
    case strikethrough = "\u{f0cc}"
    case underline = "\u{f0cd}"
    case table = "\u{f0ce}"
    case magic = "\u{f0d0}"
    case truck = "\u{f0d1}"
    case pinterest = "\u{f0d2}"
    case pinterestSquare = "\u{f0d3}"
    case googlePlusSquare = "\u{f0d4}"
    case googlePlus = "\u{f0d5}"
    case money = "\u{f0d6}"
    case caretDown = "\u{f0d7}"
    case caretUp = "\u{f0d8}"
    case caretLeft = "\u{f0d9}"
    case caretRight = "\u{f0da}"
    case columns = "\u{f0db}"
    case sort = "\u{f0dc}"
    static var unsorted: FontAwesome { return .sort }
    case sortDesc = "\u{f0dd}"
    static var sortDown: FontAwesome { return .sortDesc }
    case sortAsc = "\u{f0de}"
    static var sortUp: FontAwesome { return .sortAsc }
    case envelope = "\u{f0e0}"
    case linkedin = "\u{f0e1}"
    case undo = "\u{f0e2}"
    static var rotateLeft: FontAwesome { return .undo }
    case gavel = "\u{f0e3}"
    static var legal: FontAwesome { return .gavel }
    case tachometer = "\u{f0e4}"
    static var dashboard: FontAwesome { return .tachometer }
    case commentO = "\u{f0e5}"
    case commentsO = "\u{f0e6}"
    case bolt = "\u{f0e7}"
    static var flash: FontAwesome { return .bolt }
    case sitemap = "\u{f0e8}"
    case umbrella = "\u{f0e9}"
    case clipboard = "\u{f0ea}"
    static var paste: FontAwesome { return .clipboard }
    case lightbulbO = "\u{f0eb}"
    case exchange = "\u{f0ec}"
    case cloudDownload = "\u{f0ed}"
    case cloudUpload = "\u{f0ee}"
    case userMd = "\u{f0f0}"
    case stethoscope = "\u{f0f1}"
    case suitcase = "\u{f0f2}"
    case bellO = "\u{f0a2}"
    case coffee = "\u{f0f4}"
    case cutlery = "\u{f0f5}"
    case fileTextO = "\u{f0f6}"
    case buildingO = "\u{f0f7}"
    case hospitalO = "\u{f0f8}"
    case ambulance = "\u{f0f9}"
    case medkit = "\u{f0fa}"
    case fighterJet = "\u{f0fb}"
    case beer = "\u{f0fc}"
    case hSquare = "\u{f0fd}"
    case plusSquare = "\u{f0fe}"
    case angleDoubleLeft = "\u{f100}"
    case angleDoubleRight = "\u{f101}"
    case angleDoubleUp = "\u{f102}"
    case angleDoubleDown = "\u{f103}"
    case angleLeft = "\u{f104}"
    case angleRight = "\u{f105}"
    case angleUp = "\u{f106}"
    case angleDown = "\u{f107}"
    case desktop = "\u{f108}"
    case laptop = "\u{f109}"
    case tablet = "\u{f10a}"
    case mobile = "\u{f10b}"
    static var mobilePhone: FontAwesome { return .mobile }
    case circleO = "\u{f10c}"
    case quoteLeft = "\u{f10d}"
    case quoteRight = "\u{f10e}"
    case spinner = "\u{f110}"
    case circle = "\u{f111}"
    case reply = "\u{f112}"
    static var mailReply: FontAwesome { return .reply }
    case githubAlt = "\u{f113}"
    case folderO = "\u{f114}"
    case folderOpenO = "\u{f115}"
    case smileO = "\u{f118}"
    case frownO = "\u{f119}"
    case mehO = "\u{f11a}"
    case gamepad = "\u{f11b}"
    case keyboardO = "\u{f11c}"
    case flagO = "\u{f11d}"
    case flagCheckered = "\u{f11e}"
    case terminal = "\u{f120}"
    case code = "\u{f121}"
    case replyAll = "\u{f122}"
    static var mailReplyAll: FontAwesome { return .replyAll }
    case starHalfO = "\u{f123}"
    static var starHalfEmpty: FontAwesome { return .starHalfO }
    static var starHalfFull: FontAwesome { return .starHalfO }
    case locationArrow = "\u{f124}"
    case crop = "\u{f125}"
    case codeFork = "\u{f126}"
    case chainBroken = "\u{f127}"
    static var unlink: FontAwesome { return .chainBroken }
    case question = "\u{f128}"
    case info = "\u{f129}"
    case exclamation = "\u{f12a}"
    case superscript = "\u{f12b}"
    case `subscript` = "\u{f12c}"
    case eraser = "\u{f12d}"
    case puzzlePiece = "\u{f12e}"
    case microphone = "\u{f130}"
    case microphoneSlash = "\u{f131}"
    case shield = "\u{f132}"
    case calendarO = "\u{f133}"
    case fireExtinguisher = "\u{f134}"
    case rocket = "\u{f135}"
    case maxcdn = "\u{f136}"
    case chevronCircleLeft = "\u{f137}"
    case chevronCircleRight = "\u{f138}"
    case chevronCircleUp = "\u{f139}"
    case chevronCircleDown = "\u{f13a}"
    case html5 = "\u{f13b}"
    case css3 = "\u{f13c}"
    case anchor = "\u{f13d}"
    case unlockAlt = "\u{f13e}"
    case bullseye = "\u{f140}"
    case ellipsisH = "\u{f141}"
    case ellipsisV = "\u{f142}"
    case rssSquare = "\u{f143}"
    case playCircle = "\u{f144}"
    case ticket = "\u{f145}"
    case minusSquare = "\u{f146}"
    case minusSquareO = "\u{f147}"
    case levelUp = "\u{f148}"
    case levelDown = "\u{f149}"
    case checkSquare = "\u{f14a}"
    case pencilSquare = "\u{f14b}"
    case externalLinkSquare = "\u{f14c}"
    case shareSquare = "\u{f14d}"
    case compass = "\u{f14e}"
    case caretSquareODown = "\u{f150}"
    static var toggleDown: FontAwesome { return .caretSquareODown }
    case caretSquareOUp = "\u{f151}"
    static var toggleUp: FontAwesome { return .caretSquareOUp }
    case caretSquareORight = "\u{f152}"
    static var toggleRight: FontAwesome { return .caretSquareORight }
    case eur = "\u{f153}"
    static var euro: FontAwesome { return .eur }
    case gbp = "\u{f154}"
    case usd = "\u{f155}"
    static var dollar: FontAwesome { return .usd }
    case inr = "\u{f156}"
    static var rupee: FontAwesome { return .inr }
    case jpy = "\u{f157}"
    static var cny: FontAwesome { return .jpy }
    static var rmb: FontAwesome { return .jpy }
    static var yen: FontAwesome { return .jpy }
    case rub = "\u{f158}"
    static var ruble: FontAwesome { return .rub }
    static var rouble: FontAwesome { return .rub }
    case krw = "\u{f159}"
    static var won: FontAwesome { return .krw }
    case btc = "\u{f15a}"
    static var bitcoin: FontAwesome { return .btc }
    case file = "\u{f15b}"
    case fileText = "\u{f15c}"
    case sortAlphaAsc = "\u{f15d}"
    case sortAlphaDesc = "\u{f15e}"
    case sortAmountAsc = "\u{f160}"
    case sortAmountDesc = "\u{f161}"
    case sortNumericAsc = "\u{f162}"
    case sortNumericDesc = "\u{f163}"
    case thumbsUp = "\u{f164}"
    case thumbsDown = "\u{f165}"
    case youtubeSquare = "\u{f166}"
    case youtube = "\u{f167}"
    case xing = "\u{f168}"
    case xingSquare = "\u{f169}"
    case youtubePlay = "\u{f16a}"
    case dropbox = "\u{f16b}"
    case stackOverflow = "\u{f16c}"
    case instagram = "\u{f16d}"
    case flickr = "\u{f16e}"
    case adn = "\u{f170}"
    case bitbucket = "\u{f171}"
    case bitbucketSquare = "\u{f172}"
    case tumblr = "\u{f173}"
    case tumblrSquare = "\u{f174}"
    case longArrowDown = "\u{f175}"
    case longArrowUp = "\u{f176}"
    case longArrowLeft = "\u{f177}"
    case longArrowRight = "\u{f178}"
    case apple = "\u{f179}"
    case windows = "\u{f17a}"
    case android = "\u{f17b}"
    case linux = "\u{f17c}"
    case dribbble = "\u{f17d}"
    case skype = "\u{f17e}"
    case foursquare = "\u{f180}"
    case trello = "\u{f181}"
    case female = "\u{f182}"
    case male = "\u{f183}"
    case gratipay = "\u{f184}"
    static var gittip: FontAwesome { return .gratipay }
    case sunO = "\u{f185}"
    case moonO = "\u{f186}"
    case archive = "\u{f187}"
    case bug = "\u{f188}"
    case vk = "\u{f189}"
    case weibo = "\u{f18a}"
    case renren = "\u{f18b}"
    case pagelines = "\u{f18c}"
    case stackExchange = "\u{f18d}"
    case arrowCircleORight = "\u{f18e}"
    case arrowCircleOLeft = "\u{f190}"
    case caretSquareOLeft = "\u{f191}"
    static var toggleLeft: FontAwesome { return .caretSquareOLeft }
    case dotCircleO = "\u{f192}"
    case wheelchair = "\u{f193}"
    case vimeoSquare = "\u{f194}"
    case `try` = "\u{f195}"
    static var turkishLira: FontAwesome { return .try }
    case plusSquareO = "\u{f196}"
    case spaceShuttle = "\u{f197}"
    case slack = "\u{f198}"
    case envelopeSquare = "\u{f199}"
    case wordpress = "\u{f19a}"
    case openid = "\u{f19b}"
    case university = "\u{f19c}"
    static var institution: FontAwesome { return .university }
    static var bank: FontAwesome { return .university }
    case graduationCap = "\u{f19d}"
    static var mortarBoard: FontAwesome { return .graduationCap }
    case yahoo = "\u{f19e}"
    case google = "\u{f1a0}"
    case reddit = "\u{f1a1}"
    case redditSquare = "\u{f1a2}"
    case stumbleuponCircle = "\u{f1a3}"
    case stumbleupon = "\u{f1a4}"
    case delicious = "\u{f1a5}"
    case digg = "\u{f1a6}"
    case piedPiperPp = "\u{f1a7}"
    case piedPiperAlt = "\u{f1a8}"
    case drupal = "\u{f1a9}"
    case joomla = "\u{f1aa}"
    case language = "\u{f1ab}"
    case fax = "\u{f1ac}"
    case building = "\u{f1ad}"
    case child = "\u{f1ae}"
    case paw = "\u{f1b0}"
    case spoon = "\u{f1b1}"
    case cube = "\u{f1b2}"
    case cubes = "\u{f1b3}"
    case behance = "\u{f1b4}"
    case behanceSquare = "\u{f1b5}"
    case steam = "\u{f1b6}"
    case steamSquare = "\u{f1b7}"
    case recycle = "\u{f1b8}"
    case car = "\u{f1b9}"
    static var automobile: FontAwesome { return .car }
    case taxi = "\u{f1ba}"
    static var cab: FontAwesome { return .taxi }
    case tree = "\u{f1bb}"
    case spotify = "\u{f1bc}"
    case deviantart = "\u{f1bd}"
    case soundcloud = "\u{f1be}"
    case database = "\u{f1c0}"
    case filePdfO = "\u{f1c1}"
    case fileWordO = "\u{f1c2}"
    case fileExcelO = "\u{f1c3}"
    case filePowerpointO = "\u{f1c4}"
    case fileImageO = "\u{f1c5}"
    static var filePhotoO: FontAwesome { return .fileImageO }
    static var filePictureO: FontAwesome { return .fileImageO }
    case fileArchiveO = "\u{f1c6}"
    static var fileZipO: FontAwesome { return .fileArchiveO }
    case fileAudioO = "\u{f1c7}"
    static var fileSoundO: FontAwesome { return .fileAudioO }
    case fileVideoO = "\u{f1c8}"
    static var fileMovieO: FontAwesome { return .fileVideoO }
    case fileCodeO = "\u{f1c9}"
    case vine = "\u{f1ca}"
    case codepen = "\u{f1cb}"
    case jsfiddle = "\u{f1cc}"
    case lifeRing = "\u{f1cd}"
    static var lifeBouy: FontAwesome { return .lifeRing }
    static var lifeBuoy: FontAwesome { return .lifeRing }
    static var lifeSaver: FontAwesome { return .lifeRing }
    static var support: FontAwesome { return .lifeRing }
    case circleONotch = "\u{f1ce}"
    case rebel = "\u{f1d0}"
    static var ra: FontAwesome { return .rebel }
    static var resistance: FontAwesome { return .rebel }
    case empire = "\u{f1d1}"
    static var ge: FontAwesome { return .empire }
    case gitSquare = "\u{f1d2}"
    case git = "\u{f1d3}"
    case hackerNews = "\u{f1d4}"
    static var yCombinatorSquare: FontAwesome { return .hackerNews }
    static var ycSquare: FontAwesome { return .hackerNews }
    case tencentWeibo = "\u{f1d5}"
    case qq = "\u{f1d6}"
    case weixin = "\u{f1d7}"
    static var wechat: FontAwesome { return .weixin }
    case paperPlane = "\u{f1d8}"
    static var send: FontAwesome { return .paperPlane }
    case paperPlaneO = "\u{f1d9}"
    static var sendO: FontAwesome { return .paperPlaneO }
    case history = "\u{f1da}"
    case circleThin = "\u{f1db}"
    case header = "\u{f1dc}"
    case paragraph = "\u{f1dd}"
    case sliders = "\u{f1de}"
    case shareAlt = "\u{f1e0}"
    case shareAltSquare = "\u{f1e1}"
    case bomb = "\u{f1e2}"
    case futbolO = "\u{f1e3}"
    static var soccerBallO: FontAwesome { return .futbolO }
    case tty = "\u{f1e4}"
    case binoculars = "\u{f1e5}"
    case plug = "\u{f1e6}"
    case slideshare = "\u{f1e7}"
    case twitch = "\u{f1e8}"
    case yelp = "\u{f1e9}"
    case newspaperO = "\u{f1ea}"
    case wifi = "\u{f1eb}"
    case calculator = "\u{f1ec}"
    case paypal = "\u{f1ed}"
    case googleWallet = "\u{f1ee}"
    case ccVisa = "\u{f1f0}"
    case ccMastercard = "\u{f1f1}"
    case ccDiscover = "\u{f1f2}"
    case ccAmex = "\u{f1f3}"
    case ccPaypal = "\u{f1f4}"
    case ccStripe = "\u{f1f5}"
    case bellSlash = "\u{f1f6}"
    case bellSlashO = "\u{f1f7}"
    case trash = "\u{f1f8}"
    case copyright = "\u{f1f9}"
    case at = "\u{f1fa}"
    case eyedropper = "\u{f1fb}"
    case paintBrush = "\u{f1fc}"
    case birthdayCake = "\u{f1fd}"
    case areaChart = "\u{f1fe}"
    case pieChart = "\u{f200}"
    case lineChart = "\u{f201}"
    case lastfm = "\u{f202}"
    case lastfmSquare = "\u{f203}"
    case toggleOff = "\u{f204}"
    case toggleOn = "\u{f205}"
    case bicycle = "\u{f206}"
    case bus = "\u{f207}"
    case ioxhost = "\u{f208}"
    case angellist = "\u{f209}"
    case cc = "\u{f20a}"
    case ils = "\u{f20b}"
    static var shekel: FontAwesome { return .ils }
    static var sheqel: FontAwesome { return .ils }
    case meanpath = "\u{f20c}"
    case buysellads = "\u{f20d}"
    case connectdevelop = "\u{f20e}"
    case dashcube = "\u{f210}"
    case forumbee = "\u{f211}"
    case leanpub = "\u{f212}"
    case sellsy = "\u{f213}"
    case shirtsinbulk = "\u{f214}"
    case simplybuilt = "\u{f215}"
    case skyatlas = "\u{f216}"
    case cartPlus = "\u{f217}"
    case cartArrowDown = "\u{f218}"
    case diamond = "\u{f219}"
    case ship = "\u{f21a}"
    case userSecret = "\u{f21b}"
    case motorcycle = "\u{f21c}"
    case streetView = "\u{f21d}"
    case heartbeat = "\u{f21e}"
    case venus = "\u{f221}"
    case mars = "\u{f222}"
    case mercury = "\u{f223}"
    case transgender = "\u{f224}"
    static var intersex: FontAwesome { return .transgender }
    case transgenderAlt = "\u{f225}"
    case venusDouble = "\u{f226}"
    case marsDouble = "\u{f227}"
    case venusMars = "\u{f228}"
    case marsStroke = "\u{f229}"
    case marsStrokeV = "\u{f22a}"
    case marsStrokeH = "\u{f22b}"
    case neuter = "\u{f22c}"
    case genderless = "\u{f22d}"
    case facebookOfficial = "\u{f230}"
    case pinterestP = "\u{f231}"
    case whatsapp = "\u{f232}"
    case server = "\u{f233}"
    case userPlus = "\u{f234}"
    case userTimes = "\u{f235}"
    case bed = "\u{f236}"
    static var hotel: FontAwesome { return .bed }
    case viacoin = "\u{f237}"
    case train = "\u{f238}"
    case subway = "\u{f239}"
    case medium = "\u{f23a}"
    case yCombinator = "\u{f23b}"
    static var yc: FontAwesome { return .yCombinator }
    case optinMonster = "\u{f23c}"
    case opencart = "\u{f23d}"
    case expeditedssl = "\u{f23e}"
    case batteryFull = "\u{f240}"
    static var battery4: FontAwesome { return .batteryFull }
    static var battery: FontAwesome { return .batteryFull }
    case batteryThreeQuarters = "\u{f241}"
    static var battery3: FontAwesome { return .batteryThreeQuarters }
    case batteryHalf = "\u{f242}"
    static var battery2: FontAwesome { return .batteryHalf }
    case batteryQuarter = "\u{f243}"
    static var battery1: FontAwesome { return .batteryQuarter }
    case batteryEmpty = "\u{f244}"
    static var battery0: FontAwesome { return .batteryEmpty }
    case mousePointer = "\u{f245}"
    case iCursor = "\u{f246}"
    case objectGroup = "\u{f247}"
    case objectUngroup = "\u{f248}"
    case stickyNote = "\u{f249}"
    case stickyNoteO = "\u{f24a}"
    case ccJcb = "\u{f24b}"
    case ccDinersClub = "\u{f24c}"
    case clone = "\u{f24d}"
    case balanceScale = "\u{f24e}"
    case hourglassO = "\u{f250}"
    case hourglassStart = "\u{f251}"
    static var hourglass1: FontAwesome { return .hourglassStart }
    case hourglassHalf = "\u{f252}"
    static var hourglass2: FontAwesome { return .hourglassHalf }
    case hourglassEnd = "\u{f253}"
    static var hourglass3: FontAwesome { return .hourglassEnd }
    case hourglass = "\u{f254}"
    case handRockO = "\u{f255}"
    static var handGrabO: FontAwesome { return .handRockO }
    case handPaperO = "\u{f256}"
    static var handStopO: FontAwesome { return .handPaperO }
    case handScissorsO = "\u{f257}"
    case handLizardO = "\u{f258}"
    case handSpockO = "\u{f259}"
    case handPointerO = "\u{f25a}"
    case handPeaceO = "\u{f25b}"
    case trademark = "\u{f25c}"
    case registered = "\u{f25d}"
    case creativeCommons = "\u{f25e}"
    case gg = "\u{f260}"
    case ggCircle = "\u{f261}"
    case tripadvisor = "\u{f262}"
    case odnoklassniki = "\u{f263}"
    case odnoklassnikiSquare = "\u{f264}"
    case getPocket = "\u{f265}"
    case wikipediaW = "\u{f266}"
    case safari = "\u{f267}"
    case chrome = "\u{f268}"
    case firefox = "\u{f269}"
    case opera = "\u{f26a}"
    case internetExplorer = "\u{f26b}"
    case television = "\u{f26c}"
    static var tv: FontAwesome { return .television }
    case contao = "\u{f26d}"
    case _500px = "\u{f26e}"
    case amazon = "\u{f270}"
    case calendarPlusO = "\u{f271}"
    case calendarMinusO = "\u{f272}"
    case calendarTimesO = "\u{f273}"
    case calendarCheckO = "\u{f274}"
    case industry = "\u{f275}"
    case mapPin = "\u{f276}"
    case mapSigns = "\u{f277}"
    case mapO = "\u{f278}"
    case map = "\u{f279}"
    case commenting = "\u{f27a}"
    case commentingO = "\u{f27b}"
    case houzz = "\u{f27c}"
    case vimeo = "\u{f27d}"
    case blackTie = "\u{f27e}"
    case fonticons = "\u{f280}"
    case redditAlien = "\u{f281}"
    case edge = "\u{f282}"
    case creditCardAlt = "\u{f283}"
    case codiepie = "\u{f284}"
    case modx = "\u{f285}"
    case fortAwesome = "\u{f286}"
    case usb = "\u{f287}"
    case productHunt = "\u{f288}"
    case mixcloud = "\u{f289}"
    case scribd = "\u{f28a}"
    case pauseCircle = "\u{f28b}"
    case pauseCircleO = "\u{f28c}"
    case stopCircle = "\u{f28d}"
    case stopCircleO = "\u{f28e}"
    case shoppingBag = "\u{f290}"
    case shoppingBasket = "\u{f291}"
    case hashtag = "\u{f292}"
    case bluetooth = "\u{f293}"
    case bluetoothB = "\u{f294}"
    case percent = "\u{f295}"
    case gitlab = "\u{f296}"
    case wpbeginner = "\u{f297}"
    case wpforms = "\u{f298}"
    case envira = "\u{f299}"
    case universalAccess = "\u{f29a}"
    case wheelchairAlt = "\u{f29b}"
    case questionCircleO = "\u{f29c}"
    case blind = "\u{f29d}"
    case audioDescription = "\u{f29e}"
    case volumeControlPhone = "\u{f2a0}"
    case braille = "\u{f2a1}"
    case assistiveListeningSystems = "\u{f2a2}"
    case americanSignLanguageInterpreting = "\u{f2a3}"
    static var aslInterpreting: FontAwesome { return .americanSignLanguageInterpreting }
    case deaf = "\u{f2a4}"
    static var deafness: FontAwesome { return .deaf }
    static var hardOfHearing: FontAwesome { return .deaf }
    case glide = "\u{f2a5}"
    case glideG = "\u{f2a6}"
    case signLanguage = "\u{f2a7}"
    static var signing: FontAwesome { return .signLanguage }
    case lowVision = "\u{f2a8}"
    case viadeo = "\u{f2a9}"
    case viadeoSquare = "\u{f2aa}"
    case snapchat = "\u{f2ab}"
    case snapchatGhost = "\u{f2ac}"
    case snapchatSquare = "\u{f2ad}"
    case piedPiper = "\u{f2ae}"
    case firstOrder = "\u{f2b0}"
    case yoast = "\u{f2b1}"
    case themeisle = "\u{f2b2}"
    case googlePlusOfficial = "\u{f2b3}"
    static var googlePlusCircle: FontAwesome { return .googlePlusOfficial }
    case fontAwesome = "\u{f2b4}"
    static var fa: FontAwesome { return .fontAwesome }
    case handshakeO = "\u{f2b5}"
    case envelopeOpen = "\u{f2b6}"
    case envelopeOpenO = "\u{f2b7}"
    case linode = "\u{f2b8}"
    case addressBook = "\u{f2b9}"
    case addressBookO = "\u{f2ba}"
    case addressCard = "\u{f2bb}"
    static var vcard: FontAwesome { return .addressCard }
    case addressCardO = "\u{f2bc}"
    static var vcardO: FontAwesome { return .addressCardO }
    case userCircle = "\u{f2bd}"
    case userCircleO = "\u{f2be}"
    case userO = "\u{f2c0}"
    case idBadge = "\u{f2c1}"
    case idCard = "\u{f2c2}"
    static var driversLicense: FontAwesome { return .idCard }
    case idCardO = "\u{f2c3}"
    static var driversLicenseO: FontAwesome { return .idCardO }
    case quora = "\u{f2c4}"
    case freeCodeCamp = "\u{f2c5}"
    case telegram = "\u{f2c6}"
    case thermometerFull = "\u{f2c7}"
    static var thermometer4: FontAwesome { return .thermometerFull }
    static var thermometer: FontAwesome { return .thermometerFull }
    case thermometerThreeQuarters = "\u{f2c8}"
    static var thermometer3: FontAwesome { return .thermometerThreeQuarters }
    case thermometerHalf = "\u{f2c9}"
    static var thermometer2: FontAwesome { return .thermometerHalf }
    case thermometerQuarter = "\u{f2ca}"
    static var thermometer1: FontAwesome { return .thermometerQuarter }
    case thermometerEmpty = "\u{f2cb}"
    static var thermometer0: FontAwesome { return .thermometerEmpty }
    case shower = "\u{f2cc}"
    case bath = "\u{f2cd}"
    static var bathtub: FontAwesome { return .bath }
    static var s15: FontAwesome { return .bath }
    case podcast = "\u{f2ce}"
    case windowMaximize = "\u{f2d0}"
    case windowMinimize = "\u{f2d1}"
    case windowRestore = "\u{f2d2}"
    case windowClose = "\u{f2d3}"
    static var timesRectangle: FontAwesome { return .windowClose }
    case windowCloseO = "\u{f2d4}"
    static var timesRectangleO: FontAwesome { return .windowCloseO }
    case bandcamp = "\u{f2d5}"
    case grav = "\u{f2d6}"
    case etsy = "\u{f2d7}"
    case imdb = "\u{f2d8}"
    case ravelry = "\u{f2d9}"
    case eercast = "\u{f2da}"
    case microchip = "\u{f2db}"
    case snowflakeO = "\u{f2dc}"
    case superpowers = "\u{f2dd}"
    case wpexplorer = "\u{f2de}"
    case meetup = "\u{f2e0}"

    static func ofSize(_ size: CGFloat) -> UIFont? {
        return UIFont(name: "FontAwesome", size: size)
    }
}
